# Generated by Django 3.0.5 on 2021-07-03 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proceso', models.IntegerField(blank=True, default=0)),
                ('unidad', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total_personas', models.SmallIntegerField(blank=True, default=0)),
                ('total_cultura', models.SmallIntegerField(blank=True, default=0)),
                ('total_liderazgo', models.SmallIntegerField(blank=True, default=0)),
                ('total_estrategia', models.SmallIntegerField(blank=True, default=0)),
                ('total_estructura', models.SmallIntegerField(blank=True, default=0)),
                ('total_operaciones', models.SmallIntegerField(blank=True, default=0)),
                ('total_creatividad', models.SmallIntegerField(blank=True, default=0)),
                ('total_tecnologia', models.SmallIntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proceso', models.IntegerField(blank=True, default=0)),
                ('p1', models.SmallIntegerField(blank=True, default=0)),
                ('p2', models.SmallIntegerField(blank=True, default=0)),
                ('p3', models.SmallIntegerField(blank=True, default=0)),
                ('p4', models.SmallIntegerField(blank=True, default=0)),
                ('p5', models.SmallIntegerField(blank=True, default=0)),
                ('p6', models.SmallIntegerField(blank=True, default=0)),
                ('p7', models.SmallIntegerField(blank=True, default=0)),
                ('p8', models.SmallIntegerField(blank=True, default=0)),
                ('p9', models.SmallIntegerField(blank=True, default=0)),
                ('p10', models.SmallIntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
