# Generated by Django 3.0.5 on 2021-07-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluaciones',
            name='nro_pilar',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
    ]
